# Generated by Django 3.2.6 on 2021-09-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_comment_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
